# general settings
name: train_DAT_x3_nl8s2
model_type: DATModel
scale: 3
num_gpu: auto
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: nl8s2
    type: PairedImageDataset
    dataroot_gt: ../../data/DAT/L8S2_train_split4/HR
    dataroot_lq: ../../data/DAT/L8S2_train_split4/LR/NL8S2
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 12
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    task: SR
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Set5/HR
    dataroot_lq: datasets/benchmark/Set5/LR_bicubic/X3
    filename_tmpl: '{}x3'
    io_backend:
      type: disk

# network structures
network_g:
  type: DAT
  upscale: 3
  in_chans: 3
  img_size: 64
  img_range: 1.
  split_size: [8,32]
  depth: [6,6,6,6,6,6]
  embed_dim: 180
  num_heads: [6,6,6,6,6,6]
  expansion_factor: 4
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: experiments/pretrained_models/DAT/DAT_x3.pth
  strict_load_g: False
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 75000, 102500, 131250, 141000]
    gamma: 0.5

  total_iter: 150000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2000
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: True

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 20000
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
